import CodeBlock from "../components/code-block";
import DocPage, { Callout, Prose, Section } from "../components/doc-page";
import Example from "../components/example";

const overrideCss = `@import "tailwindcss";
@import "components-ui/styles.css";

/* Later @theme declarations win - override any token */
@theme {
  --color-primary-50: oklch(96.9% 0.016 293.756);
  --color-primary-100: oklch(94.3% 0.029 294.588);
  --color-primary-200: oklch(89.4% 0.057 293.283);
  --color-primary-300: oklch(81.1% 0.111 293.571);
  --color-primary-400: oklch(70.2% 0.183 293.541);
  --color-primary-500: oklch(60.6% 0.25 292.717);
  --color-primary-600: oklch(54.1% 0.281 293.009);
  --color-primary-700: oklch(49.1% 0.27 292.581);
  --color-primary-800: oklch(43.2% 0.232 292.759);
  --color-primary-900: oklch(38% 0.189 293.745);
  --color-primary-950: oklch(28.3% 0.141 291.089);

  /* Page background and the surface of cards, dialogs and popovers */
  --color-background: #f8fafc;
  --color-surface: #ffffff;
}`;

const reuseTailwind = `@theme {
  /* Or simply map the scale onto one of Tailwind's palettes */
  --color-primary-500: var(--color-violet-500);
  --color-primary-600: var(--color-violet-600);
  /* … and the other shades */
}`;

const darkClass = `/* Dark mode by a class on <html> instead of the system setting */
@custom-variant dark (&:where(.dark, .dark *));`;

const helpers = `<a className="btn" href="/signup">Sign up</a>   /* a link styled as the primary button */
<div className="btn-group">…</div>              /* joins adjacent buttons / fields */
<div className="rich-text" />                   /* renders the HTML of RichTextEditor */
<input className="form-control" />              /* the look of the library's fields */`;

export default function Theming() {
  return (
    <DocPage
      description="The components are styled with Tailwind classes that read a small set of color tokens. Change the tokens and every component follows."
      title="Theming"
    >
      <Section title="Color tokens">
        <Prose>
          <p>
            Seven scales from 50 to 950 - <code>primary</code> (buttons, focus
            rings, selection), <code>secondary</code>, <code>success</code>,{" "}
            <code>danger</code>, <code>warning</code>, <code>info</code> and{" "}
            <code>neutral</code> - plus <code>background</code> /{" "}
            <code>surface</code> and their <code>-dark</code> variants. They are
            Tailwind theme variables, so they also work in your own classes:{" "}
            <code>bg-primary-500</code>, <code>text-danger-600</code>, …
          </p>
        </Prose>
        <Example collapsed name="theming/tokens" title="The default palette" />
      </Section>

      <Section title="Your brand colors">
        <Prose>
          <p>
            Override the tokens after importing the library's stylesheet. The
            example below does the same on a single element to preview a few
            palettes.
          </p>
        </Prose>
        <CodeBlock code={overrideCss} />
        <CodeBlock className="mt-4" code={reuseTailwind} />
        <Example
          collapsed
          name="theming/palettes"
          title="Previewing palettes"
        />
      </Section>

      <Section title="Dark mode">
        <Prose>
          <p>
            Every component has <code>dark:</code> styles. By default Tailwind
            applies them by the system setting (
            <code>prefers-color-scheme</code>). To switch it in the app - as
            these docs do - use a class:
          </p>
        </Prose>
        <CodeBlock code={darkClass} />
        <Callout>
          <p>
            The <code>dark:</code> classes of the components are generated by
            your Tailwind build, so the variant you configure applies to them
            too.
          </p>
        </Callout>
      </Section>

      <Section title="Sizes of the app layout">
        <Prose>
          <p>
            The drawer width comes from CSS variables:{" "}
            <code>--drawer-width</code> (240px) and{" "}
            <code>--drawer-collapsed-width</code> (64px).
          </p>
        </Prose>
      </Section>

      <Section title="Helper classes">
        <Prose>
          <p>The stylesheet also defines a few classes for your own markup:</p>
        </Prose>
        <CodeBlock code={helpers} plain />
      </Section>

      <Section title="Adjusting a single component">
        <Prose>
          <p>
            Every component accepts <code>className</code>, merged after its own
            classes. Where a conflicting utility does not win by the cascade,
            use Tailwind's important modifier (<code>bg-red-500!</code>).
          </p>
        </Prose>
      </Section>
    </DocPage>
  );
}
