/** Static options shared by the Autocomplete examples. */
export const cities = [
  "Amsterdam",
  "Barcelona",
  "Berlin",
  "Bratislava",
  "Brno",
  "Budapest",
  "Göteborg",
  "Kraków",
  "København",
  "Lisboa",
  "Ljubljana",
  "Łódź",
  "Málaga",
  "München",
  "Oslo",
  "Paris",
  "Plzeň",
  "Praha",
  "Reykjavík",
  "Rīga",
  "Roma",
  "São Paulo",
  "Tallinn",
  "Warszawa",
  "Wien",
  "Zürich",
].map((city) => ({ label: city, value: city.toLowerCase() }));
