import { useId } from "react";
import cn, { joinTokens } from "../../utils/cn";
import { isControlTarget } from "./control-target";
import FormDescription from "./form-description";
import FormError from "./form-error";
import RequiredMark from "./required-mark";
import { useMessages } from "../../providers/ui-context";

/** Whether a slot renders anything - the `false` of a condition does not. */
const hasContent = (node: React.ReactNode) =>
  node !== undefined && node !== null && node !== false && node !== "";

/**
 * What `Field` passes to its control - spread it on the element that takes
 * the focus.
 */
export interface FieldControlProps {
  /** Ids of the error message and the description - in this order. */
  "aria-describedby"?: string;
  /** `"true"` while the field has an `error`. */
  "aria-invalid"?: "true";
  /**
   * Id of the label - it also names a control a `<label>` cannot, like a
   * `div` with a role.
   */
  "aria-labelledby"?: string;
  /** `"true"` for a `required` field. */
  "aria-required"?: "true";
  /** Present (empty) while the field has an `error` - for your styles. */
  "data-invalid"?: "";
  /** The id the label points at. */
  id: string;
}

export interface FieldProps extends Omit<
  React.ComponentProps<"div">,
  "children"
> {
  /**
   * The control. A function gets the id and the ARIA attributes to spread
   * on it (`FieldControlProps`); an element has to use them itself - the
   * `id`, `${id}-description` and `${id}-error`.
   */
  children:
    React.ReactNode | ((controlProps: FieldControlProps) => React.ReactNode);
  /**
   * Classes of the wrapper around the label, the control, the description
   * and the error message.
   */
  className?: string;
  /** Help text under the control - it describes the control. */
  description?: React.ReactNode;
  /** Validation message - also marks the control as invalid. */
  error?: string;
  /**
   * Id of the control - generated by default. The label points at it, and
   * the ids of the description (`${id}-description`) and the error message
   * (`${id}-error`) derive from it.
   */
  id?: string;
  /**
   * The `<label>` above the control - a text, or content like a text with
   * an icon. It names the control by `aria-labelledby` too.
   */
  label?: React.ReactNode;
  /**
   * Marks the label with a star and the control with `aria-required` - the
   * control itself still has to be `required` for the browser to check it.
   */
  required?: boolean;
}

/**
 * The label, the description and the error message of the library's
 * fields, for a control of your own or of another library - with the ids
 * connecting them: `<Field label="…">{(controlProps) => <Control
 * {...controlProps} />}</Field>`.
 */
export default function Field({
  children,
  className,
  description,
  error,
  id,
  label,
  required,
  ...props
}: FieldProps) {
  const messages = useMessages().ui;
  const generatedId = useId();
  const controlId = id ?? generatedId;
  const labelId = `${controlId}-label`;
  const errorId = error ? `${controlId}-error` : undefined;
  const descriptionId = description ? `${controlId}-description` : undefined;
  const hasLabel = hasContent(label);

  const controlProps: FieldControlProps = {
    "aria-describedby": joinTokens(errorId, descriptionId),
    "aria-invalid": error ? "true" : undefined,
    "aria-labelledby": hasLabel ? labelId : undefined,
    "aria-required": required ? "true" : undefined,
    "data-invalid": error ? "" : undefined,
    id: controlId,
  };

  return (
    <div {...props} className={cn("flex flex-col gap-1.5", className)}>
      {hasLabel && (
        <label
          className="block truncate text-sm font-medium"
          htmlFor={controlId}
          id={labelId}
          // A control no label reaches (a `div` with a role) gets the focus
          // from a click on the label too, as an input would - not from one
          // on a button or a link in the label (or in a popover it opens),
          // which is theirs alone
          onClick={(event) => {
            const labelElement = event.currentTarget;
            if (
              !labelElement.control &&
              !isControlTarget(event.target, labelElement)
            ) {
              labelElement.ownerDocument.getElementById(controlId)?.focus();
            }
          }}
        >
          {label}
          {messages.form.labelSuffix}{" "}
          {/* The star is for the eye - `required` tells assistive technology */}
          {required && <RequiredMark />}
        </label>
      )}

      {typeof children === "function" ? children(controlProps) : children}

      <FormDescription id={descriptionId}>{description}</FormDescription>
      {error && <FormError id={errorId}>{error}</FormError>}
    </div>
  );
}
